"""Constants for the Fluidra Z250iQ integration."""

from __future__ import annotations

from datetime import timedelta

DOMAIN = "fluidra_z250iq"

CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_DEVICE_ID = "device_id"
CONF_DEVICE_NAME = "device_name"
CONF_SCAN_INTERVAL = "scan_interval"

DEFAULT_SCAN_INTERVAL = timedelta(minutes=5)
MIN_SCAN_INTERVAL = timedelta(minutes=2)
MAX_SCAN_INTERVAL = timedelta(minutes=15)
TOKEN_REFRESH_MARGIN = timedelta(minutes=1)

API_BASE_URL = "https://api.fluidra-emea.com"
API_ENDPOINT_DEVICES = f"{API_BASE_URL}/generic/devices?deviceType=connected"
API_ENDPOINT_DEVICE_DETAIL = (
    f"{API_BASE_URL}/generic/devices/{{device_id}}?deviceType=connected"
)
API_ENDPOINT_DEVICE_COMPONENTS = (
    f"{API_BASE_URL}/generic/devices/{{device_id}}/components?deviceType=connected"
)
API_ENDPOINT_DEVICE_UICONFIG = (
    f"{API_BASE_URL}/generic/devices/{{device_id}}/uiconfig?appId=iaq&deviceType=connected"
)
API_ENDPOINT_SET_COMPONENT = (
    f"{API_BASE_URL}/generic/devices/{{device_id}}/components/{{component_id}}"
    "?deviceType=connected"
)

WS_URL = "wss://ws.fluidra-emea.com"
WS_RECONNECT_DELAY = 5

COGNITO_REGION = "eu-west-1"
COGNITO_CLIENT_ID = "g3njunelkcbtefosqm9bdhhq1"

COMPONENT_RUNNING_HOURS = 0
COMPONENT_ACTIVE = 11
COMPONENT_INTERNAL_TIMESTAMP = 12
COMPONENT_POWER = 13
COMPONENT_MODE = 14
COMPONENT_SETPOINT = 15
COMPONENT_CONTROL_SUBMODE = 16
COMPONENT_TIMER_FLAG = 17
COMPONENT_AUXILIARY_FLAG = 18
COMPONENT_WATER_TEMP = 19
COMPONENT_NO_FLOW = 28
COMPONENT_INTERNAL_METRIC_60 = 60
COMPONENT_INTERNAL_METRIC_61 = 61
COMPONENT_AIR_TEMP = 67
COMPONENT_WATER_INLET_TEMP = 68
COMPONENT_WATER_OUTLET_TEMP = 69
COMPONENT_HOT_SIDE_TEMP = 65
COMPONENT_COLD_SIDE_TEMP = 66
COMPONENT_COLD_SIDE_TEMP_2 = 70
COMPONENT_MACHINE_METRIC_72 = 72
COMPONENT_MACHINE_METRIC_73 = 73
COMPONENT_SUPPLY_VOLTAGE = 74
COMPONENT_INTERNAL_METRIC_75 = 75
COMPONENT_MACHINE_METRIC_76 = 76
COMPONENT_MACHINE_POWER = 64
COMPONENT_MACHINE_CURRENT = 77
COMPONENT_INTERNAL_METRIC_78 = 78
COMPONENT_INTERNAL_METRIC_79 = 79
COMPONENT_EFFECTIVE_MODE = 80
COMPONENT_SETPOINT_MIN = 81
COMPONENT_SETPOINT_MAX = 82

MODE_SMART_HEATING = 0
MODE_SMART_COOLING = 1
MODE_SMART_AUTO = 2
MODE_BOOST_HEATING = 3
MODE_SILENCE_HEATING = 4
MODE_BOOST_COOLING = 5
MODE_SILENCE_COOLING = 6

MODE_LABELS = {
    MODE_SMART_HEATING: "Smart Heating",
    MODE_SMART_COOLING: "Smart Cooling",
    MODE_SMART_AUTO: "Smart Auto",
    MODE_BOOST_HEATING: "Boost Heating",
    MODE_SILENCE_HEATING: "Silence Heating",
    MODE_BOOST_COOLING: "Boost Cooling",
    MODE_SILENCE_COOLING: "Silence Cooling",
}

PRESET_TO_MODE = {label: mode for mode, label in MODE_LABELS.items()}
HEATING_MODE_VALUES = {
    MODE_SMART_HEATING,
    MODE_BOOST_HEATING,
    MODE_SILENCE_HEATING,
}
COOLING_MODE_VALUES = {
    MODE_SMART_COOLING,
    MODE_BOOST_COOLING,
    MODE_SILENCE_COOLING,
}

SUPPORTED_MODEL_HINTS = ("z250iq",)
SUPPORTED_SKUS = ("WH000589",)
